/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JTable;
import javax.swing.JTextField;

/**
 *
 * @author Peter Louis
 */
public class Buscarcliente extends javax.swing.JFrame {

    /**
     * Creates new form Buscarcliente
     */
    public Buscarcliente() {
        initComponents();
    }

    public JPanel getjPanebuscarcliente() {
        return jPanebuscarcliente;
    }

    public void setjPanebuscarcliente(JPanel jPanebuscarcliente) {
        this.jPanebuscarcliente = jPanebuscarcliente;
    }

    public JTable getjTablebuscarcliente() {
        return jTablebuscarcliente;
    }

    public void setjTablebuscarcliente(JTable jTablebuscarcliente) {
        this.jTablebuscarcliente = jTablebuscarcliente;
    }

    public JTextField getjTexbuscarcliente() {
        return jTexbuscarcliente;
    }

    public void setjTexbuscarcliente(JTextField jTexbuscarcliente) {
        this.jTexbuscarcliente = jTexbuscarcliente;
    }
    

    public JLabel getjLabuscarcliente() {
        return jLabuscarcliente;
    }

    public void setjLabuscarcliente(JLabel jLabuscarcliente) {
        this.jLabuscarcliente = jLabuscarcliente;
    }

    public JPanel getjPanel1() {
        return jPanebuscarcliente;
    }

    public void setjPanel1(JPanel jPanel1) {
        this.jPanebuscarcliente = jPanel1;
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanebuscarcliente = new javax.swing.JPanel();
        jLabuscarcliente = new javax.swing.JLabel();
        jTexbuscarcliente = new javax.swing.JTextField();
        jLablbuscarcliente = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTablebuscarcliente = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanebuscarcliente.setBackground(new java.awt.Color(255, 51, 0));
        jPanebuscarcliente.setForeground(new java.awt.Color(255, 102, 51));
        jPanebuscarcliente.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N

        jLabuscarcliente.setText("BUSCAR CLIENTE");

        jLablbuscarcliente.setText("Buscar Cliente");

        jTablebuscarcliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jTablebuscarcliente);

        javax.swing.GroupLayout jPanebuscarclienteLayout = new javax.swing.GroupLayout(jPanebuscarcliente);
        jPanebuscarcliente.setLayout(jPanebuscarclienteLayout);
        jPanebuscarclienteLayout.setHorizontalGroup(
            jPanebuscarclienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanebuscarclienteLayout.createSequentialGroup()
                .addGap(159, 159, 159)
                .addComponent(jLabuscarcliente, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(140, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanebuscarclienteLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLablbuscarcliente, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTexbuscarcliente, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanebuscarclienteLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanebuscarclienteLayout.setVerticalGroup(
            jPanebuscarclienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanebuscarclienteLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabuscarcliente, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanebuscarclienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTexbuscarcliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLablbuscarcliente))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 275, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanebuscarcliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanebuscarcliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLablbuscarcliente;
    private javax.swing.JLabel jLabuscarcliente;
    private javax.swing.JPanel jPanebuscarcliente;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTablebuscarcliente;
    private javax.swing.JTextField jTexbuscarcliente;
    // End of variables declaration//GEN-END:variables
}
