/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import javax.swing.JButton;
import javax.swing.JPanel;
import javax.swing.JTable;
import javax.swing.JTextField;

/**
 *
 * @author Peter Louis
 */
public class Buscarusuario extends javax.swing.JFrame {

    /**
     * Creates new form Buscarusuario
     */
    public Buscarusuario() {
        initComponents();
    }

    public JTable getjTablebuscarusuario() {
        return jTablebuscarusuario;
    }

    public void setjTablebuscarusuario(JTable jTablebuscarusuario) {
        this.jTablebuscarusuario = jTablebuscarusuario;
    }

    

    

    public JTextField getjTextbuscarusuario() {
        return jTextbuscarusuario;
    }

    public void setjTextbuscarusuario(JTextField jTextbuscarusuario) {
        this.jTextbuscarusuario = jTextbuscarusuario;
    }
   
    public JPanel getjPanebuscarusuario() {
        return jPanebuscarusuario;
    }

    public void setjPanebuscarusuario(JPanel jPanebuscarusuario) {
        this.jPanebuscarusuario = jPanebuscarusuario;
    }

    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanebuscarusuario = new javax.swing.JPanel();
        jLabebuscarusuario = new javax.swing.JLabel();
        jTextbuscarusuario = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTablebuscarusuario = new javax.swing.JTable();
        jLabeb = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanebuscarusuario.setBackground(new java.awt.Color(255, 0, 204));
        jPanebuscarusuario.setForeground(new java.awt.Color(0, 0, 204));

        jLabebuscarusuario.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabebuscarusuario.setText("Buscar Usuario");

        jTablebuscarusuario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jTablebuscarusuario);

        jLabeb.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabeb.setText("Buscar Usuario");

        javax.swing.GroupLayout jPanebuscarusuarioLayout = new javax.swing.GroupLayout(jPanebuscarusuario);
        jPanebuscarusuario.setLayout(jPanebuscarusuarioLayout);
        jPanebuscarusuarioLayout.setHorizontalGroup(
            jPanebuscarusuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanebuscarusuarioLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabeb, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 87, Short.MAX_VALUE)
                .addComponent(jTextbuscarusuario, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
            .addGroup(jPanebuscarusuarioLayout.createSequentialGroup()
                .addGap(156, 156, 156)
                .addComponent(jLabebuscarusuario)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanebuscarusuarioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanebuscarusuarioLayout.setVerticalGroup(
            jPanebuscarusuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanebuscarusuarioLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabebuscarusuario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanebuscarusuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextbuscarusuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanebuscarusuarioLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabeb, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 279, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanebuscarusuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanebuscarusuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabeb;
    private javax.swing.JLabel jLabebuscarusuario;
    private javax.swing.JPanel jPanebuscarusuario;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTablebuscarusuario;
    private javax.swing.JTextField jTextbuscarusuario;
    // End of variables declaration//GEN-END:variables
}
