/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JTable;
import javax.swing.JTextField;

/**
 *
 * @author Peter Louis
 */
public class Buscarproveedor extends javax.swing.JFrame {

    /**
     * Creates new form Buscarproveedor
     */
    public Buscarproveedor() {
        initComponents();
    }

    public JPanel getjPanebuscarproveedor() {
        return jPanebuscarproveedor;
    }

    public void setjPanebuscarproveedor(JPanel jPanebuscarproveedor) {
        this.jPanebuscarproveedor = jPanebuscarproveedor;
    }

    public JTable getjTablebuscarproveedor() {
        return jTablebuscarproveedor;
    }

    public void setjTablebuscarproveedor(JTable jTablebuscarproveedor) {
        this.jTablebuscarproveedor = jTablebuscarproveedor;
    }

    public JTextField getjTextbuscarproveedor() {
        return jTextbuscarproveedor;
    }

    public void setjTextbuscarproveedor(JTextField jTextbuscarproveedor) {
        this.jTextbuscarproveedor = jTextbuscarproveedor;
    }
    

    public JButton getjButbuscarprovee() {
        return jButbuscarprovee;
    }

    public void setjButbuscarprovee(JButton jButbuscarprovee) {
        this.jButbuscarprovee = jButbuscarprovee;
    }
    

    public JLabel getjLabel1() {
        return jLabel1;
    }

    public void setjLabel1(JLabel jLabel1) {
        this.jLabel1 = jLabel1;
    }

    public JPanel getjPanel1() {
        return jPanebuscarproveedor;
    }

    public void setjPanel1(JPanel jPanel1) {
        this.jPanebuscarproveedor = jPanel1;
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanebuscarproveedor = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButbuscarprovee = new javax.swing.JButton();
        jTextbuscarproveedor = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTablebuscarproveedor = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanebuscarproveedor.setBackground(new java.awt.Color(0, 102, 102));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel1.setText("BUSCAR PROVEEDOR");

        jButbuscarprovee.setBackground(new java.awt.Color(153, 51, 0));
        jButbuscarprovee.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jButbuscarprovee.setText("Buscar");

        jTablebuscarproveedor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jTablebuscarproveedor);

        javax.swing.GroupLayout jPanebuscarproveedorLayout = new javax.swing.GroupLayout(jPanebuscarproveedor);
        jPanebuscarproveedor.setLayout(jPanebuscarproveedorLayout);
        jPanebuscarproveedorLayout.setHorizontalGroup(
            jPanebuscarproveedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanebuscarproveedorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButbuscarprovee, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 115, Short.MAX_VALUE)
                .addComponent(jTextbuscarproveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43))
            .addGroup(jPanebuscarproveedorLayout.createSequentialGroup()
                .addGap(118, 118, 118)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanebuscarproveedorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
        );
        jPanebuscarproveedorLayout.setVerticalGroup(
            jPanebuscarproveedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanebuscarproveedorLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanebuscarproveedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButbuscarprovee, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextbuscarproveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 275, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanebuscarproveedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanebuscarproveedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButbuscarprovee;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanebuscarproveedor;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTablebuscarproveedor;
    private javax.swing.JTextField jTextbuscarproveedor;
    // End of variables declaration//GEN-END:variables
}
