/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import javax.swing.JButton;
import javax.swing.JPanel;
import javax.swing.JTable;
import javax.swing.JTextField;

/**
 *
 * @author Peter Louis
 */
public class Detallefactura extends javax.swing.JFrame {

    /**
     * Creates new form Detallefactura
     */
    public Detallefactura() {
        initComponents();
    }

    public JButton getjButagregarfactura() {
        return jButagregarfactura;
    }

    public void setjButagregarfactura(JButton jButagregarfactura) {
        this.jButagregarfactura = jButagregarfactura;
    }

    public JButton getjButiconobuscarproducto() {
        return jButiconobuscarproducto;
    }

    public void setjButiconobuscarproducto(JButton jButiconobuscarproducto) {
        this.jButiconobuscarproducto = jButiconobuscarproducto;
    }

    

    public JPanel getjPandetallefactura() {
        return jPandetallefactura;
    }

    public void setjPandetallefactura(JPanel jPandetallefactura) {
        this.jPandetallefactura = jPandetallefactura;
    }

    public JTable getjTabagregardetallefactura() {
        return jTabagregardetallefactura;
    }

    public void setjTabagregardetallefactura(JTable jTabagregardetallefactura) {
        this.jTabagregardetallefactura = jTabagregardetallefactura;
    }

    public JTextField getjTexnumerodefactura() {
        return jTexnumerodefactura;
    }

    public void setjTexnumerodefactura(JTextField jTexnumerodefactura) {
        this.jTexnumerodefactura = jTexnumerodefactura;
    }

    public JTextField getjTexpreciounitario() {
        return jTexpreciounitario;
    }

    public void setjTexpreciounitario(JTextField jTexpreciounitario) {
        this.jTexpreciounitario = jTexpreciounitario;
    }

    public JTextField getJexcantidadcomprada() {
        return jexcantidadcomprada;
    }

    public void setJexcantidadcomprada(JTextField jexcantidadcomprada) {
        this.jexcantidadcomprada = jexcantidadcomprada;
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPandetallefactura = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabdetallefactura = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jexcantidadcomprada = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTexpreciounitario = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTexnumerodefactura = new javax.swing.JTextField();
        jButagregarfactura = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTabagregardetallefactura = new javax.swing.JTable();
        jButiconobuscarproducto = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPandetallefactura.setBackground(new java.awt.Color(0, 204, 204));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel1.setText("Producto");

        jLabdetallefactura.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabdetallefactura.setText("Agregar Detalle Factura");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel2.setText("Cantidad Comprada");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel3.setText("Precio Unitario");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel4.setText("Numero de Factura");

        jButagregarfactura.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jButagregarfactura.setText("Agregar");

        jTabagregardetallefactura.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jTabagregardetallefactura);

        javax.swing.GroupLayout jPandetallefacturaLayout = new javax.swing.GroupLayout(jPandetallefactura);
        jPandetallefactura.setLayout(jPandetallefacturaLayout);
        jPandetallefacturaLayout.setHorizontalGroup(
            jPandetallefacturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPandetallefacturaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPandetallefacturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jButiconobuscarproducto, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPandetallefacturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPandetallefacturaLayout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(jTexnumerodefactura, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButagregarfactura, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(133, 133, 133))
                    .addGroup(jPandetallefacturaLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(44, 44, 44)
                        .addComponent(jexcantidadcomprada, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)
                        .addComponent(jTexpreciounitario, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40))))
            .addGroup(jPandetallefacturaLayout.createSequentialGroup()
                .addGap(300, 300, 300)
                .addComponent(jLabdetallefactura, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPandetallefacturaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jPandetallefacturaLayout.setVerticalGroup(
            jPandetallefacturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPandetallefacturaLayout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addComponent(jLabdetallefactura)
                .addGap(18, 18, 18)
                .addGroup(jPandetallefacturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jexcantidadcomprada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jTexpreciounitario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButiconobuscarproducto, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(jPandetallefacturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPandetallefacturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4)
                        .addComponent(jTexnumerodefactura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButagregarfactura, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPandetallefactura, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPandetallefactura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 7, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButagregarfactura;
    private javax.swing.JButton jButiconobuscarproducto;
    private javax.swing.JLabel jLabdetallefactura;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPandetallefactura;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTabagregardetallefactura;
    private javax.swing.JTextField jTexnumerodefactura;
    private javax.swing.JTextField jTexpreciounitario;
    private javax.swing.JTextField jexcantidadcomprada;
    // End of variables declaration//GEN-END:variables
}
