/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import javax.swing.JButton;
import javax.swing.JPanel;
import javax.swing.JTextArea;
import javax.swing.JTextField;

/**
 *
 * @author Peter Louis
 */
public class Nuevo_Producto extends javax.swing.JFrame {

    /**
     * Creates new form Nuevo_Producto
     */
    public Nuevo_Producto() {
        initComponents();
    }

    public JTextField getTxtbuscarimagenproducto() {
        return txtbuscarimagenproducto;
    }

    public void setTxtbuscarimagenproducto(JTextField txtbuscarimagenproducto) {
        this.txtbuscarimagenproducto = txtbuscarimagenproducto;
    }
    
    

    public JPanel getjPanenuevoproducto() {
        return jPanenuevoproducto;
    }

    public void setjPanenuevoproducto(JPanel jPanenuevoproducto) {
        this.jPanenuevoproducto = jPanenuevoproducto;
    }

    public JTextArea getTxtdescriprocdu() {
        return txtdescriprocdu;
    }

    public void setTxtdescriprocdu(JTextArea txtdescriprocdu) {
        this.txtdescriprocdu = txtdescriprocdu;
    }

    public JTextField getTxtimagenproducto() {
        return txtbuscarimagenproducto;
    }

    public void setTxtimagenproducto(JTextField txtimagenproducto) {
        this.txtbuscarimagenproducto = txtimagenproducto;
    }
    

    public JButton getCancelar() {
        return jbtncancelar;
    }

    public void setCancelar(JButton Cancelar) {
        this.jbtncancelar = Cancelar;
    }

    public JButton getJbtnGuardarproducto() {
        return jbtnGuardar;
    }

    public void setJbtnGuardarproducto(JButton jbtnGuardarproducto) {
        this.jbtnGuardar = jbtnGuardarproducto;
    }

    public JButton getGuardar() {
        return jbtnGuardar;
    }

    public void setGuardar(JButton Guardar) {
        this.jbtnGuardar = Guardar;
    }
    

    public JButton getButbuscarimagen() {
        return btnbuscarimagen;
    }

    public void setButbuscarimagen(JButton butbuscarimagen) {
        this.btnbuscarimagen = butbuscarimagen;
    }

   

    public JTextArea getTxtdescr() {
        return txtdescriprocdu;
    }

    public void setTxtdescr(JTextArea txtdescr) {
        this.txtdescriprocdu = txtdescr;
    }

    public JTextField getTxtimagen() {
        return txtbuscarimagenproducto;
    }

    public void setTxtimagen(JTextField txtimagen) {
        this.txtbuscarimagenproducto = txtimagen;
    }

    public JTextField getTxtnombre() {
        return txtnombre;
    }

    public void setTxtnombre(JTextField txtnombre) {
        this.txtnombre = txtnombre;
    }

    public JButton getBtnbuscarimagen() {
        return btnbuscarimagen;
    }

    public void setBtnbuscarimagen(JButton btnbuscarimagen) {
        this.btnbuscarimagen = btnbuscarimagen;
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tiendacom1 = new Modelo.Tiendacom();
        jPanenuevoproducto = new javax.swing.JPanel();
        jLabelnuevoproducto = new javax.swing.JLabel();
        labNombre = new javax.swing.JLabel();
        txtnombre = new javax.swing.JTextField();
        Imagen = new javax.swing.JLabel();
        txtbuscarimagenproducto = new javax.swing.JTextField();
        Descripcion = new javax.swing.JLabel();
        jbtncancelar = new javax.swing.JButton();
        jbtnGuardar = new javax.swing.JButton();
        btnbuscarimagen = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtdescriprocdu = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanenuevoproducto.setBackground(new java.awt.Color(255, 102, 0));

        jLabelnuevoproducto.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabelnuevoproducto.setText("Nuevo Producto");

        labNombre.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        labNombre.setText("Nombre");

        Imagen.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        Imagen.setText("Imagen");

        Descripcion.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        Descripcion.setText("Descripcion");

        jbtncancelar.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jbtncancelar.setForeground(new java.awt.Color(0, 0, 153));
        jbtncancelar.setText("Cancelar");

        jbtnGuardar.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jbtnGuardar.setForeground(new java.awt.Color(0, 0, 204));
        jbtnGuardar.setText("Guardar");

        btnbuscarimagen.setBackground(new java.awt.Color(204, 255, 255));
        btnbuscarimagen.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        btnbuscarimagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/botonbuscar.png"))); // NOI18N

        txtdescriprocdu.setColumns(20);
        txtdescriprocdu.setRows(5);
        jScrollPane1.setViewportView(txtdescriprocdu);

        javax.swing.GroupLayout jPanenuevoproductoLayout = new javax.swing.GroupLayout(jPanenuevoproducto);
        jPanenuevoproducto.setLayout(jPanenuevoproductoLayout);
        jPanenuevoproductoLayout.setHorizontalGroup(
            jPanenuevoproductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanenuevoproductoLayout.createSequentialGroup()
                .addGroup(jPanenuevoproductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanenuevoproductoLayout.createSequentialGroup()
                        .addComponent(jbtncancelar)
                        .addGap(201, 201, 201)
                        .addComponent(jbtnGuardar)
                        .addGap(11, 11, 11))
                    .addGroup(jPanenuevoproductoLayout.createSequentialGroup()
                        .addGroup(jPanenuevoproductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(Descripcion, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE)
                            .addComponent(Imagen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(labNombre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(37, 37, 37)
                        .addGroup(jPanenuevoproductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanenuevoproductoLayout.createSequentialGroup()
                                .addComponent(txtbuscarimagenproducto, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(40, 40, 40)
                                .addComponent(btnbuscarimagen, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabelnuevoproducto, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtnombre, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 50, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanenuevoproductoLayout.setVerticalGroup(
            jPanenuevoproductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanenuevoproductoLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabelnuevoproducto)
                .addGap(18, 18, 18)
                .addGroup(jPanenuevoproductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labNombre)
                    .addComponent(txtnombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanenuevoproductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanenuevoproductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Imagen)
                        .addComponent(txtbuscarimagenproducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnbuscarimagen, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanenuevoproductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanenuevoproductoLayout.createSequentialGroup()
                        .addGap(111, 111, 111)
                        .addComponent(Descripcion)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 98, Short.MAX_VALUE)
                        .addComponent(jbtncancelar))
                    .addGroup(jPanenuevoproductoLayout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jbtnGuardar)))
                .addGap(49, 49, 49))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanenuevoproducto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanenuevoproducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Descripcion;
    private javax.swing.JLabel Imagen;
    private javax.swing.JButton btnbuscarimagen;
    private javax.swing.JLabel jLabelnuevoproducto;
    private javax.swing.JPanel jPanenuevoproducto;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbtnGuardar;
    private javax.swing.JButton jbtncancelar;
    private javax.swing.JLabel labNombre;
    private Modelo.Tiendacom tiendacom1;
    private javax.swing.JTextField txtbuscarimagenproducto;
    private javax.swing.JTextArea txtdescriprocdu;
    private javax.swing.JTextField txtnombre;
    // End of variables declaration//GEN-END:variables
}
