/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JTextField;

/**
 *
 * @author Peter Louis
 */
public class Nuevos_Usuarios extends javax.swing.JFrame {

    /**
     * Creates new form Nuevos_Usuarios
     */
    public Nuevos_Usuarios() {
        initComponents();
    }

    public JButton getBtnOjo() {
        return btnOjo;
    }

    public void setBtnOjo(JButton btnOjo) {
        this.btnOjo = btnOjo;
    }

    public JComboBox<String> getCbSexo() {
        return cobSexo;
    }

    public void setCbSexo(JComboBox<String> cbSexo) {
        this.cobSexo = cbSexo;
    }

    public JComboBox<String> getCbtipoDocu() {
        return cbtipoDocu;
    }

    public void setCbtipoDocu(JComboBox<String> cbtipoDocu) {
        this.cbtipoDocu = cbtipoDocu;
    }

    public JPanel getJpNuevoUsuario() {
        return jpNuevoUsuario;
    }

    public void setJpNuevoUsuario(JPanel jpNuevoUsuario) {
        this.jpNuevoUsuario = jpNuevoUsuario;
    }

    public JLabel getLblNuevoUsuario() {
        return lblNuevoUsuario;
    }

    public void setLblNuevoUsuario(JLabel lblNuevoUsuario) {
        this.lblNuevoUsuario = lblNuevoUsuario;
    }

    public JTextField getTxtdocumento() {
        return txtdocumento;
    }

    public void setTxtdocumento(JTextField txtdocumento) {
        this.txtdocumento = txtdocumento;
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpNuevoUsuario = new javax.swing.JPanel();
        lblNuevoUsuario = new javax.swing.JLabel();
        lbltipoDocumento = new javax.swing.JLabel();
        cbtipoDocu = new javax.swing.JComboBox<>();
        lbldocumento = new javax.swing.JLabel();
        txtdocumento = new javax.swing.JTextField();
        btnOjo = new javax.swing.JButton();
        lblsexo = new javax.swing.JLabel();
        cobSexo = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtTelefono = new javax.swing.JTextField();
        leCorreo = new javax.swing.JLabel();
        txtCorreo = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtDireccion = new javax.swing.JTextField();
        laClave = new javax.swing.JLabel();
        jpasClave = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();
        jboGuardar = new javax.swing.JButton();
        jboCancelar = new javax.swing.JButton();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jLaCargo = new javax.swing.JLabel();
        jComCargo = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblNuevoUsuario.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        lblNuevoUsuario.setText("Nuevo Usuario");

        lbltipoDocumento.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        lbltipoDocumento.setForeground(new java.awt.Color(51, 102, 255));
        lbltipoDocumento.setText("Tipo de Documento");

        cbtipoDocu.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        cbtipoDocu.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione...", "Cedula", "Cedula extranjeria ", "Pasaporte" }));

        lbldocumento.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        lbldocumento.setForeground(new java.awt.Color(51, 102, 255));
        lbldocumento.setText("Documento");

        btnOjo.setIcon(new javax.swing.ImageIcon("C:\\Users\\Peter Louis\\Documents\\NetBeansProjects\\Tiendacom\\src\\main\\resources\\img\\foto.png")); // NOI18N

        lblsexo.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        lblsexo.setForeground(new java.awt.Color(51, 102, 255));
        lblsexo.setText("Sexo");

        cobSexo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cobSexoActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 102, 255));
        jLabel1.setText("Nombre");

        txtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 102, 255));
        jLabel2.setText("Telefono");

        leCorreo.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        leCorreo.setForeground(new java.awt.Color(51, 102, 255));
        leCorreo.setText("Correo");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 102, 255));
        jLabel3.setText("Direccion");

        laClave.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        laClave.setForeground(new java.awt.Color(51, 102, 255));
        laClave.setText("Clave");

        jpasClave.setText("jPasswordField2");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 102, 255));
        jLabel4.setText("Fecha de nacimiento");

        jboGuardar.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jboGuardar.setText("Guardar");

        jboCancelar.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jboCancelar.setText("Cancerlar");

        jLaCargo.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLaCargo.setForeground(new java.awt.Color(51, 102, 255));
        jLaCargo.setText("Cargo");

        jComCargo.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jComCargo.setForeground(new java.awt.Color(51, 102, 255));
        jComCargo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione su cargo", "Administrador", "Cliente", "Usuario" }));

        javax.swing.GroupLayout jpNuevoUsuarioLayout = new javax.swing.GroupLayout(jpNuevoUsuario);
        jpNuevoUsuario.setLayout(jpNuevoUsuarioLayout);
        jpNuevoUsuarioLayout.setHorizontalGroup(
            jpNuevoUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpNuevoUsuarioLayout.createSequentialGroup()
                .addGroup(jpNuevoUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jpNuevoUsuarioLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnOjo))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jpNuevoUsuarioLayout.createSequentialGroup()
                        .addGap(114, 114, 114)
                        .addComponent(lblNuevoUsuario)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jpNuevoUsuarioLayout.createSequentialGroup()
                        .addGroup(jpNuevoUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jpNuevoUsuarioLayout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addGroup(jpNuevoUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(laClave, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(leCorreo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lbltipoDocumento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblsexo)
                                    .addComponent(lbldocumento, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(jpNuevoUsuarioLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jboGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLaCargo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jpNuevoUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpNuevoUsuarioLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(jpNuevoUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtdocumento)
                                    .addComponent(cbtipoDocu, 0, 198, Short.MAX_VALUE)
                                    .addComponent(cobSexo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtNombre)
                                    .addComponent(txtTelefono)
                                    .addComponent(txtCorreo)
                                    .addComponent(txtDireccion)
                                    .addComponent(jpasClave)
                                    .addComponent(jDateChooser1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jboCancelar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jComCargo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(22, 22, 22))
        );
        jpNuevoUsuarioLayout.setVerticalGroup(
            jpNuevoUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpNuevoUsuarioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblNuevoUsuario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpNuevoUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jpNuevoUsuarioLayout.createSequentialGroup()
                        .addGroup(jpNuevoUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jpNuevoUsuarioLayout.createSequentialGroup()
                                .addGroup(jpNuevoUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lbltipoDocumento)
                                    .addComponent(cbtipoDocu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jpNuevoUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtdocumento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbldocumento))
                                .addGap(18, 18, 18)
                                .addComponent(lblsexo))
                            .addComponent(cobSexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jpNuevoUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpNuevoUsuarioLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel1))
                            .addGroup(jpNuevoUsuarioLayout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jpNuevoUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(12, 12, 12)
                        .addGroup(jpNuevoUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(leCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jpNuevoUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtDireccion)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jpNuevoUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(laClave)
                            .addComponent(jpasClave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4))
                    .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnOjo)
                .addGap(21, 21, 21)
                .addGroup(jpNuevoUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLaCargo)
                    .addComponent(jComCargo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jpNuevoUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jboGuardar)
                    .addComponent(jboCancelar))
                .addGap(17, 17, 17))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jpNuevoUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jpNuevoUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cobSexoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cobSexoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cobSexoActionPerformed

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreActionPerformed

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnOjo;
    private javax.swing.JComboBox<String> cbtipoDocu;
    private javax.swing.JComboBox<String> cobSexo;
    private javax.swing.JComboBox<String> jComCargo;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLaCargo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JButton jboCancelar;
    private javax.swing.JButton jboGuardar;
    private javax.swing.JPanel jpNuevoUsuario;
    private javax.swing.JPasswordField jpasClave;
    private javax.swing.JLabel laClave;
    private javax.swing.JLabel lblNuevoUsuario;
    private javax.swing.JLabel lbldocumento;
    private javax.swing.JLabel lblsexo;
    private javax.swing.JLabel lbltipoDocumento;
    private javax.swing.JLabel leCorreo;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JTextField txtDireccion;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtTelefono;
    private javax.swing.JTextField txtdocumento;
    // End of variables declaration//GEN-END:variables
}
