/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import com.toedter.calendar.JDateChooser;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JPanel;
import javax.swing.JTextField;

/**
 *
 * @author Peter Louis
 */
public class Nuevo_proveedor extends javax.swing.JFrame {

    /**
     * Creates new form Nuevo_proveedor
     */
    public Nuevo_proveedor() {
        initComponents();
    }
    

    public JPanel getjPanenuevoproveedor() {
        return jPanenuevoproveedor;
    }

    public void setjPanenuevoproveedor(JPanel jPanenuevoproveedor) {
        this.jPanenuevoproveedor = jPanenuevoproveedor;
    }
    
    

    public JButton getBotcancelar() {
        return botcancelar;
    }

    public void setBotcancelar(JButton botcancelar) {
        this.botcancelar = botcancelar;
    }

    public JButton getBotguardar() {
        return botguardar;
    }

    public void setBotguardar(JButton botguardar) {
        this.botguardar = botguardar;
    }

    public JComboBox<String> getjCombsexo() {
        return jCombsexo;
    }

    public void setjCombsexo(JComboBox<String> jCombsexo) {
        this.jCombsexo = jCombsexo;
    }

    public JTextField getjTexcorreo() {
        return jTexcorreo;
    }

    public void setjTexcorreo(JTextField jTexcorreo) {
        this.jTexcorreo = jTexcorreo;
    }
    

    public JComboBox<String> getjComtipodedocumento() {
        return jComtipodedocumento;
    }

    public void setjComtipodedocumento(JComboBox<String> jComtipodedocumento) {
        this.jComtipodedocumento = jComtipodedocumento;
    }

    public JTextField getjTexdocumento() {
        return jTexdocumento;
    }

    public void setjTexdocumento(JTextField jTexdocumento) {
        this.jTexdocumento = jTexdocumento;
    }
    

    public JTextField getjTextField1() {
        return jTexdocumento;
    }

    public void setjTextField1(JTextField jTextField1) {
        this.jTexdocumento = jTextField1;
    }

    public JTextField getjTextdireccion() {
        return jTextdireccion;
    }

    public void setjTextdireccion(JTextField jTextdireccion) {
        this.jTextdireccion = jTextdireccion;
    }

    public JTextField getjTextelefono() {
        return jTextelefono;
    }

    public void setjTextelefono(JTextField jTextelefono) {
        this.jTextelefono = jTextelefono;
    }

    public JTextField getjTextnombre() {
        return jTextnombre;
    }

    public void setjTextnombre(JTextField jTextnombre) {
        this.jTextnombre = jTextnombre;
    }

    public JDateChooser getjDateChfehanaci() {
        return jDateChfehanaci;
    }

    public void setjDateChfehanaci(JDateChooser jDateChfehanaci) {
        this.jDateChfehanaci = jDateChfehanaci;
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanenuevoproveedor = new javax.swing.JPanel();
        jLabnuevoproveedor = new javax.swing.JLabel();
        Documento = new javax.swing.JLabel();
        Nombre = new javax.swing.JLabel();
        jTextnombre = new javax.swing.JTextField();
        Telefono = new javax.swing.JLabel();
        jTextelefono = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jComtipodedocumento = new javax.swing.JComboBox<>();
        Sexo = new javax.swing.JLabel();
        jCombsexo = new javax.swing.JComboBox<>();
        Direccion = new javax.swing.JLabel();
        jTextdireccion = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jDateChfehanaci = new com.toedter.calendar.JDateChooser();
        botcancelar = new javax.swing.JButton();
        botguardar = new javax.swing.JButton();
        jLabcorreo = new javax.swing.JLabel();
        jTexcorreo = new javax.swing.JTextField();
        jTexdocumento = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanenuevoproveedor.setBackground(new java.awt.Color(153, 0, 153));

        jLabnuevoproveedor.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabnuevoproveedor.setText("Nuevo Proveedor");

        Documento.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        Documento.setText("Documento");

        Nombre.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        Nombre.setText("Nombre");

        Telefono.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        Telefono.setText("Telefono");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel2.setText("Tipo de Documento");

        jComtipodedocumento.setBackground(new java.awt.Color(204, 204, 0));
        jComtipodedocumento.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jComtipodedocumento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione su Documento", "Cedula", "Tarjeta de Identidad", "Registro Civil" }));

        Sexo.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        Sexo.setText("Sexo");

        jCombsexo.setBackground(new java.awt.Color(204, 204, 0));
        jCombsexo.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jCombsexo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione su Sexo", "Masculino", "Femenino", "Otro" }));

        Direccion.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        Direccion.setText("Direccion");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel3.setText("Fecha de Nacimiento");

        botcancelar.setBackground(new java.awt.Color(0, 51, 51));
        botcancelar.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        botcancelar.setForeground(new java.awt.Color(0, 255, 51));
        botcancelar.setText("Cancelar");

        botguardar.setBackground(new java.awt.Color(0, 51, 51));
        botguardar.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        botguardar.setForeground(new java.awt.Color(0, 204, 51));
        botguardar.setText("Guardar");

        jLabcorreo.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabcorreo.setText("Correo");

        javax.swing.GroupLayout jPanenuevoproveedorLayout = new javax.swing.GroupLayout(jPanenuevoproveedor);
        jPanenuevoproveedor.setLayout(jPanenuevoproveedorLayout);
        jPanenuevoproveedorLayout.setHorizontalGroup(
            jPanenuevoproveedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanenuevoproveedorLayout.createSequentialGroup()
                .addGroup(jPanenuevoproveedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanenuevoproveedorLayout.createSequentialGroup()
                        .addGroup(jPanenuevoproveedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(Direccion, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanenuevoproveedorLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(Sexo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Telefono, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Nombre, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Documento, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanenuevoproveedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextnombre)
                            .addComponent(jTextelefono)
                            .addComponent(jCombsexo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jComtipodedocumento, 0, 289, Short.MAX_VALUE)
                            .addComponent(jTexdocumento)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanenuevoproveedorLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jTextdireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanenuevoproveedorLayout.createSequentialGroup()
                        .addGroup(jPanenuevoproveedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanenuevoproveedorLayout.createSequentialGroup()
                                .addGap(117, 117, 117)
                                .addComponent(jLabnuevoproveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanenuevoproveedorLayout.createSequentialGroup()
                                .addGap(37, 37, 37)
                                .addComponent(botcancelar)
                                .addGap(97, 97, 97)
                                .addComponent(botguardar)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanenuevoproveedorLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanenuevoproveedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanenuevoproveedorLayout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jDateChfehanaci, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanenuevoproveedorLayout.createSequentialGroup()
                                .addComponent(jLabcorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTexcorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        jPanenuevoproveedorLayout.setVerticalGroup(
            jPanenuevoproveedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanenuevoproveedorLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabnuevoproveedor)
                .addGap(18, 18, 18)
                .addGroup(jPanenuevoproveedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Documento)
                    .addComponent(jTexdocumento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanenuevoproveedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Nombre)
                    .addComponent(jTextnombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanenuevoproveedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Telefono)
                    .addComponent(jTextelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanenuevoproveedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jComtipodedocumento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(jPanenuevoproveedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Sexo)
                    .addComponent(jCombsexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanenuevoproveedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabcorreo)
                    .addComponent(jTexcorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanenuevoproveedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Direccion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextdireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanenuevoproveedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(jDateChfehanaci, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(65, 65, 65)
                .addGroup(jPanenuevoproveedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botcancelar)
                    .addComponent(botguardar))
                .addContainerGap(68, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanenuevoproveedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanenuevoproveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Direccion;
    private javax.swing.JLabel Documento;
    private javax.swing.JLabel Nombre;
    private javax.swing.JLabel Sexo;
    private javax.swing.JLabel Telefono;
    private javax.swing.JButton botcancelar;
    private javax.swing.JButton botguardar;
    private javax.swing.JComboBox<String> jCombsexo;
    private javax.swing.JComboBox<String> jComtipodedocumento;
    private com.toedter.calendar.JDateChooser jDateChfehanaci;
    private javax.swing.JLabel jLabcorreo;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabnuevoproveedor;
    private javax.swing.JPanel jPanenuevoproveedor;
    private javax.swing.JTextField jTexcorreo;
    private javax.swing.JTextField jTexdocumento;
    private javax.swing.JTextField jTextdireccion;
    private javax.swing.JTextField jTextelefono;
    private javax.swing.JTextField jTextnombre;
    // End of variables declaration//GEN-END:variables
}
