/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;
import javax.swing.JButton;
import javax.swing.JPanel;
import javax.swing.JTabbedPane;
import javax.swing.JTable;
import javax.swing.JTextField;

/**
 *
 * @author user
 */
public class Principal extends javax.swing.JFrame {

    public JButton getBuscarprovedor() {
        return Buscarprovedor;
    }

    public JTabbedPane getjTable_pricipal() {
        return jTable_pricipal;
    }

    public void setjTable_pricipal(JTabbedPane jTable_pricipal) {
        this.jTable_pricipal = jTable_pricipal;
    }

    public void setBuscarprovedor(JButton Buscarprovedor) {
        this.Buscarprovedor = Buscarprovedor;
    }

    public JPanel getNuevaventa() {
        return Nuevaventa;
    }

    public void setNuevaventa(JPanel Nuevaventa) {
        this.Nuevaventa = Nuevaventa;
    }

    public JButton getBtnNuevarfactura() {
        return btnNuevarfactura;
    }

    public void setBtnNuevarfactura(JButton btnNuevarfactura) {
        this.btnNuevarfactura = btnNuevarfactura;
    }

    public JButton getBtnNuevo() {
        return btnNuevousuario;
    }

    public void setBtnNuevo(JButton btnNuevo) {
        this.btnNuevousuario = btnNuevo;
    }

    public JButton getBtnNuevoproducto() {
        return btnNuevoproducto;
    }

    public void setBtnNuevoproducto(JButton btnNuevoproducto) {
        this.btnNuevoproducto = btnNuevoproducto;
    }

    public JButton getBtnnuevacompra() {
        return btnnuevacompra;
    }

    public void setBtnnuevacompra(JButton btnnuevacompra) {
        this.btnnuevacompra = btnnuevacompra;
    }

    public JButton getBtnnuevaventa() {
        return btnnuevaventa;
    }

    public void setBtnnuevaventa(JButton btnnuevaventa) {
        this.btnnuevaventa = btnnuevaventa;
    }

    public JButton getBtnnuevocliente() {
        return btnnuevocliente;
    }

    public void setBtnnuevocliente(JButton btnnuevocliente) {
        this.btnnuevocliente = btnnuevocliente;
    }

    public JPanel getjPanel2() {
        return jPanel2;
    }

    public void setjPanel2(JPanel jPanel2) {
        this.jPanel2 = jPanel2;
    }

    public JPanel getjPanel3() {
        return jPanel3;
    }

    public void setjPanel3(JPanel jPanel3) {
        this.jPanel3 = jPanel3;
    }

    public JPanel getjPanel7() {
        return jPanel7;
    }

    public void setjPanel7(JPanel jPanel7) {
        this.jPanel7 = jPanel7;
    }

    public JTable getjTableCliente() {
        return jTableCliente;
    }

    public void setjTableCliente(JTable jTableCliente) {
        this.jTableCliente = jTableCliente;
    }

    public JTextField getTxtBuscarfactura() {
        return txtBuscarfactura;
    }

    public JButton getBtnproveedor() {
        return btnproveedor;
    }

    public void setBtnproveedor(JButton btnproveedor) {
        this.btnproveedor = btnproveedor;
    }

    public void setTxtBuscarfactura(JTextField txtBuscarfactura) {
        this.txtBuscarfactura = txtBuscarfactura;
    }

    public JTextField getTxtBuscarproducto() {
        return txtBuscarproducto;
    }

    public void setTxtBuscarproducto(JTextField txtBuscarproducto) {
        this.txtBuscarproducto = txtBuscarproducto;
    }

    public JTextField getTxtbuscarUsuario() {
        return txtbuscarUsuario;
    }

    public void setTxtbuscarUsuario(JTextField txtbuscarUsuario) {
        this.txtbuscarUsuario = txtbuscarUsuario;
    }

    
  
    
    

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        textField1 = new java.awt.TextField();
        jPanel2 = new javax.swing.JPanel();
        jLabtiendacom = new javax.swing.JLabel();
        jTable_pricipal = new javax.swing.JTabbedPane();
        jtUsuario = new javax.swing.JPanel();
        btnNuevousuario = new javax.swing.JButton();
        txtbuscarusuario = new javax.swing.JTextField();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTableUsuario = new javax.swing.JTable();
        jtCliente = new javax.swing.JPanel();
        jtxtBuscarcliente = new javax.swing.JTextField();
        btnnuevocliente = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTablCliente = new javax.swing.JTable();
        jScrollPane7 = new javax.swing.JScrollPane();
        jTableCliente = new javax.swing.JTable();
        jtabPreoveedor = new javax.swing.JPanel();
        Buscarprovedor = new javax.swing.JButton();
        btnproveedor = new javax.swing.JButton();
        jtProducto = new javax.swing.JPanel();
        btnNuevoproducto = new javax.swing.JButton();
        txtBuscarproducto = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTableProducto = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        btnnuevacompra = new javax.swing.JButton();
        txtbuscarUsuario = new javax.swing.JTextField();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTableCompra = new javax.swing.JTable();
        Nuevaventa = new javax.swing.JPanel();
        btnnuevaventa = new javax.swing.JButton();
        jTexbuscarusuario = new javax.swing.JTextField();
        jScrollPane8 = new javax.swing.JScrollPane();
        jTableVenta = new javax.swing.JTable();
        jPanel7 = new javax.swing.JPanel();
        btnNuevarfactura = new javax.swing.JButton();
        txtBuscarfactura = new javax.swing.JTextField();
        jScrollPane9 = new javax.swing.JScrollPane();
        jTableFactura = new javax.swing.JTable();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        textField1.setText("textField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabtiendacom.setText("TIENDACOM");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(226, 226, 226)
                .addComponent(jLabtiendacom, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(306, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(94, Short.MAX_VALUE)
                .addComponent(jLabtiendacom)
                .addContainerGap())
        );

        jTable_pricipal.setForeground(new java.awt.Color(51, 0, 0));

        btnNuevousuario.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        btnNuevousuario.setForeground(new java.awt.Color(51, 51, 255));
        btnNuevousuario.setText("Nuevo Usuario");
        btnNuevousuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevousuarioActionPerformed(evt);
            }
        });

        txtbuscarusuario.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        txtbuscarusuario.setForeground(new java.awt.Color(51, 51, 255));
        txtbuscarusuario.setText("Buscar Usuario");

        jTableUsuario.setForeground(new java.awt.Color(102, 0, 102));
        jTableUsuario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane5.setViewportView(jTableUsuario);

        javax.swing.GroupLayout jtUsuarioLayout = new javax.swing.GroupLayout(jtUsuario);
        jtUsuario.setLayout(jtUsuarioLayout);
        jtUsuarioLayout.setHorizontalGroup(
            jtUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jtUsuarioLayout.createSequentialGroup()
                .addComponent(btnNuevousuario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtbuscarusuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(847, 847, 847))
            .addGroup(jtUsuarioLayout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(888, Short.MAX_VALUE))
        );
        jtUsuarioLayout.setVerticalGroup(
            jtUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jtUsuarioLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jtUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNuevousuario)
                    .addComponent(txtbuscarusuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTable_pricipal.addTab("USUARIO", jtUsuario);

        jtxtBuscarcliente.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jtxtBuscarcliente.setForeground(new java.awt.Color(0, 51, 255));
        jtxtBuscarcliente.setText("Buscarcliente");

        btnnuevocliente.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        btnnuevocliente.setForeground(new java.awt.Color(0, 51, 255));
        btnnuevocliente.setText("Nuevocliente");
        btnnuevocliente.setActionCommand("nuevocliente");

        jTablCliente.setForeground(new java.awt.Color(153, 0, 102));
        jTablCliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane3.setViewportView(jTablCliente);

        jTableCliente.setForeground(new java.awt.Color(0, 153, 51));
        jTableCliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane7.setViewportView(jTableCliente);

        javax.swing.GroupLayout jtClienteLayout = new javax.swing.GroupLayout(jtCliente);
        jtCliente.setLayout(jtClienteLayout);
        jtClienteLayout.setHorizontalGroup(
            jtClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jtClienteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jtClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jtClienteLayout.createSequentialGroup()
                        .addComponent(btnnuevocliente)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jtxtBuscarcliente, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane7, javax.swing.GroupLayout.DEFAULT_SIZE, 480, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 911, Short.MAX_VALUE))
        );
        jtClienteLayout.setVerticalGroup(
            jtClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jtClienteLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jtClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxtBuscarcliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnnuevocliente))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jtClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTable_pricipal.addTab("CLIENTE", jtCliente);

        jtabPreoveedor.setForeground(new java.awt.Color(0, 153, 153));

        Buscarprovedor.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        Buscarprovedor.setForeground(new java.awt.Color(0, 102, 255));
        Buscarprovedor.setText("Buscarprovedor");

        btnproveedor.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        btnproveedor.setText("Nuevo");

        javax.swing.GroupLayout jtabPreoveedorLayout = new javax.swing.GroupLayout(jtabPreoveedor);
        jtabPreoveedor.setLayout(jtabPreoveedorLayout);
        jtabPreoveedorLayout.setHorizontalGroup(
            jtabPreoveedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jtabPreoveedorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnproveedor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 1144, Short.MAX_VALUE)
                .addComponent(Buscarprovedor)
                .addGap(50, 50, 50))
        );
        jtabPreoveedorLayout.setVerticalGroup(
            jtabPreoveedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jtabPreoveedorLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jtabPreoveedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Buscarprovedor)
                    .addComponent(btnproveedor))
                .addContainerGap(331, Short.MAX_VALUE))
        );

        jTable_pricipal.addTab("PROVEEDOR", jtabPreoveedor);

        btnNuevoproducto.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        btnNuevoproducto.setForeground(new java.awt.Color(0, 51, 255));
        btnNuevoproducto.setText("Nuevoproducto");

        txtBuscarproducto.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        txtBuscarproducto.setForeground(new java.awt.Color(51, 51, 255));
        txtBuscarproducto.setText("Buscarproducto");

        jTableProducto.setForeground(new java.awt.Color(0, 102, 102));
        jTableProducto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane4.setViewportView(jTableProducto);

        javax.swing.GroupLayout jtProductoLayout = new javax.swing.GroupLayout(jtProducto);
        jtProducto.setLayout(jtProductoLayout);
        jtProductoLayout.setHorizontalGroup(
            jtProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jtProductoLayout.createSequentialGroup()
                .addGap(222, 222, 222)
                .addGroup(jtProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jtProductoLayout.createSequentialGroup()
                        .addComponent(btnNuevoproducto, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(131, 131, 131)
                        .addComponent(txtBuscarproducto))
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(729, Short.MAX_VALUE))
        );
        jtProductoLayout.setVerticalGroup(
            jtProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jtProductoLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jtProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnNuevoproducto)
                    .addComponent(txtBuscarproducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTable_pricipal.addTab("PRODUCTO", jtProducto);

        btnnuevacompra.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        btnnuevacompra.setForeground(new java.awt.Color(51, 51, 255));
        btnnuevacompra.setText("Nuevacompra");

        txtbuscarUsuario.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        txtbuscarUsuario.setForeground(new java.awt.Color(51, 51, 255));
        txtbuscarUsuario.setText("BuscarUsuario");

        jTableCompra.setForeground(new java.awt.Color(255, 102, 102));
        jTableCompra.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane6.setViewportView(jTableCompra);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 507, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                        .addComponent(btnnuevacompra)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtbuscarUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(890, 890, 890))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtbuscarUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnnuevacompra))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTable_pricipal.addTab("COMPRA", jPanel3);

        Nuevaventa.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N

        btnnuevaventa.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        btnnuevaventa.setForeground(new java.awt.Color(102, 0, 255));
        btnnuevaventa.setText("Nueva venta");
        btnnuevaventa.setToolTipText("");

        jTexbuscarusuario.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jTexbuscarusuario.setForeground(new java.awt.Color(102, 0, 204));
        jTexbuscarusuario.setText("Buscar Usuario");

        jTableVenta.setForeground(new java.awt.Color(255, 102, 255));
        jTableVenta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane8.setViewportView(jTableVenta);

        javax.swing.GroupLayout NuevaventaLayout = new javax.swing.GroupLayout(Nuevaventa);
        Nuevaventa.setLayout(NuevaventaLayout);
        NuevaventaLayout.setHorizontalGroup(
            NuevaventaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NuevaventaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(NuevaventaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane8)
                    .addGroup(NuevaventaLayout.createSequentialGroup()
                        .addComponent(btnnuevaventa)
                        .addGap(329, 329, 329)
                        .addComponent(jTexbuscarusuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(846, Short.MAX_VALUE))
        );
        NuevaventaLayout.setVerticalGroup(
            NuevaventaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NuevaventaLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(NuevaventaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnnuevaventa)
                    .addComponent(jTexbuscarusuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTable_pricipal.addTab("VENTA", Nuevaventa);

        btnNuevarfactura.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        btnNuevarfactura.setForeground(new java.awt.Color(51, 51, 255));
        btnNuevarfactura.setText("Nuevarfactura");

        txtBuscarfactura.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        txtBuscarfactura.setForeground(new java.awt.Color(51, 51, 255));
        txtBuscarfactura.setText("Buscarfactura");
        txtBuscarfactura.setToolTipText("");

        jTableFactura.setForeground(new java.awt.Color(0, 255, 102));
        jTableFactura.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane9.setViewportView(jTableFactura);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(130, 130, 130)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(btnNuevarfactura, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(253, 253, 253)
                        .addComponent(txtBuscarfactura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane9))
                .addContainerGap(782, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNuevarfactura)
                    .addComponent(txtBuscarfactura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTable_pricipal.addTab("FACTURA", jPanel7);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jTable_pricipal)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(jTable_pricipal, javax.swing.GroupLayout.PREFERRED_SIZE, 395, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTable_pricipal.getAccessibleContext().setAccessibleName("VENTA");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNuevousuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevousuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnNuevousuarioActionPerformed

    public JTable getjTableUsuario() {
        return jTableUsuario;
    }

    public void setjTableUsuario(JTable jTableUsuario) {
        this.jTableUsuario = jTableUsuario;
    }

    public JButton getBtnNuevousuario() {
        return btnNuevousuario;
    }

    public void setBtnNuevousuario(JButton btnNuevousuario) {
        this.btnNuevousuario = btnNuevousuario;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Buscarprovedor;
    private javax.swing.JPanel Nuevaventa;
    private javax.swing.JButton btnNuevarfactura;
    private javax.swing.JButton btnNuevoproducto;
    private javax.swing.JButton btnNuevousuario;
    private javax.swing.JButton btnnuevacompra;
    private javax.swing.JButton btnnuevaventa;
    private javax.swing.JButton btnnuevocliente;
    private javax.swing.JButton btnproveedor;
    private javax.swing.JLabel jLabtiendacom;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JTable jTablCliente;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTableCliente;
    private javax.swing.JTable jTableCompra;
    private javax.swing.JTable jTableFactura;
    private javax.swing.JTable jTableProducto;
    private javax.swing.JTable jTableUsuario;
    private javax.swing.JTable jTableVenta;
    private javax.swing.JTabbedPane jTable_pricipal;
    private javax.swing.JTextField jTexbuscarusuario;
    private javax.swing.JPanel jtCliente;
    private javax.swing.JPanel jtProducto;
    private javax.swing.JPanel jtUsuario;
    private javax.swing.JPanel jtabPreoveedor;
    private javax.swing.JTextField jtxtBuscarcliente;
    private java.awt.TextField textField1;
    private javax.swing.JTextField txtBuscarfactura;
    private javax.swing.JTextField txtBuscarproducto;
    private javax.swing.JTextField txtbuscarUsuario;
    private javax.swing.JTextField txtbuscarusuario;
    // End of variables declaration//GEN-END:variables

 
}
