/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import javax.swing.JLabel;

/**
 *
 * @author Peter Louis
 */
public class Ver_detalle_factura extends javax.swing.JFrame {

    /**
     * Creates new form Ver_detalle_factura
     */
    public Ver_detalle_factura() {
        initComponents();
    }

    public JLabel getjLabmostrarfactura() {
        return jLabmostrarfactura;
    }

    public void setjLabmostrarfactura(JLabel jLabmostrarfactura) {
        this.jLabmostrarfactura = jLabmostrarfactura;
    }

    public JLabel getjLabmostrarfecha() {
        return jLabmostrarfecha;
    }

    public void setjLabmostrarfecha(JLabel jLabmostrarfecha) {
        this.jLabmostrarfecha = jLabmostrarfecha;
    }

    public JLabel getjLabmostrarproveedor() {
        return jLabmostrarproveedor;
    }

    public void setjLabmostrarproveedor(JLabel jLabmostrarproveedor) {
        this.jLabmostrarproveedor = jLabmostrarproveedor;
    }

    public JLabel getjLabmostrarusuario() {
        return jLabmostrarusuario;
    }

    public void setjLabmostrarusuario(JLabel jLabmostrarusuario) {
        this.jLabmostrarusuario = jLabmostrarusuario;
    }

    public JLabel getjLacomprobante() {
        return jLacomprobante;
    }

    public void setjLacomprobante(JLabel jLacomprobante) {
        this.jLacomprobante = jLacomprobante;
    }

    public JLabel getLbamostipodepago() {
        return lbamostipodepago;
    }

    public void setLbamostipodepago(JLabel lbamostipodepago) {
        this.lbamostipodepago = lbamostipodepago;
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPandetallefactura = new javax.swing.JPanel();
        jLabdetallefactura = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jSeparadordetallefactura = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabledetallefactura = new javax.swing.JTable();
        jLabmostrarfecha = new javax.swing.JLabel();
        jLabmostrarusuario = new javax.swing.JLabel();
        jLacomprobante = new javax.swing.JLabel();
        jLabmostrarfactura = new javax.swing.JLabel();
        jLabmostrarproveedor = new javax.swing.JLabel();
        lbamostipodepago = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPandetallefactura.setBackground(new java.awt.Color(255, 153, 102));

        jLabdetallefactura.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabdetallefactura.setText("Detalle Factura");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel1.setText("Factura");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel2.setText("Proveedor");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel3.setText("Tipo de Pago");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel4.setText("Usuario");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel5.setText("Comprobante");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel6.setText("Fecha");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel7.setText("Impuesto");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel8.setText("Valor a Pagar");

        tabledetallefactura.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tabledetallefactura);

        jLabmostrarfecha.setText("jLabel9");

        jLabmostrarusuario.setText("jLabel9");

        jLacomprobante.setText("jLabel9");

        jLabmostrarfactura.setText("jLabel9");

        jLabmostrarproveedor.setText("jLabel9");

        lbamostipodepago.setText("jLabel9");

        javax.swing.GroupLayout jPandetallefacturaLayout = new javax.swing.GroupLayout(jPandetallefactura);
        jPandetallefactura.setLayout(jPandetallefacturaLayout);
        jPandetallefacturaLayout.setHorizontalGroup(
            jPandetallefacturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPandetallefacturaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPandetallefacturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPandetallefacturaLayout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabmostrarproveedor))
                    .addGroup(jPandetallefacturaLayout.createSequentialGroup()
                        .addGroup(jPandetallefacturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 85, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPandetallefacturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabmostrarfactura)
                            .addComponent(lbamostipodepago))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPandetallefacturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPandetallefacturaLayout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(jLabmostrarusuario))
                    .addGroup(jPandetallefacturaLayout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(jLacomprobante))
                    .addGroup(jPandetallefacturaLayout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(50, 50, 50)
                        .addComponent(jLabmostrarfecha, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(196, 196, 196))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPandetallefacturaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPandetallefacturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPandetallefacturaLayout.createSequentialGroup()
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparadordetallefactura, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(121, 121, 121))
            .addGroup(jPandetallefacturaLayout.createSequentialGroup()
                .addGroup(jPandetallefacturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPandetallefacturaLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 839, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPandetallefacturaLayout.createSequentialGroup()
                        .addGap(319, 319, 319)
                        .addComponent(jLabdetallefactura)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPandetallefacturaLayout.setVerticalGroup(
            jPandetallefacturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPandetallefacturaLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabdetallefactura)
                .addGap(20, 20, 20)
                .addGroup(jPandetallefacturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPandetallefacturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabmostrarfactura))
                    .addGroup(jPandetallefacturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel6)
                        .addComponent(jLabmostrarfecha)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPandetallefacturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4)
                    .addComponent(jLabmostrarusuario)
                    .addComponent(jLabmostrarproveedor))
                .addGroup(jPandetallefacturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPandetallefacturaLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPandetallefacturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(lbamostipodepago)))
                    .addGroup(jPandetallefacturaLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(jPandetallefacturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jLacomprobante))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(jPandetallefacturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSeparadordetallefactura, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPandetallefacturaLayout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(37, 37, 37))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPandetallefactura, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(jPandetallefactura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(94, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabdetallefactura;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabmostrarfactura;
    private javax.swing.JLabel jLabmostrarfecha;
    private javax.swing.JLabel jLabmostrarproveedor;
    private javax.swing.JLabel jLabmostrarusuario;
    private javax.swing.JLabel jLacomprobante;
    private javax.swing.JPanel jPandetallefactura;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparadordetallefactura;
    private javax.swing.JLabel lbamostipodepago;
    private javax.swing.JTable tabledetallefactura;
    // End of variables declaration//GEN-END:variables
}
